# Generated by Django 2.1.5 on 2019-01-15 17:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UF',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sigla', models.CharField(max_length=2, validators=[django.core.validators.MinLengthValidator(2)])),
                ('nome', models.CharField(max_length=60)),
            ],
            options={
                'db_table': 'c_uf',
            },
        ),
    ]
