# Generated by Django 2.1.5 on 2019-01-15 20:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('endereco', '0002_endereco_uf_fixture'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endereco',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cep', models.PositiveIntegerField(default=0, verbose_name='CEP')),
                ('logradouro', models.CharField(max_length=120)),
                ('numero', models.PositiveIntegerField(default=0, verbose_name='Número')),
                ('complemento', models.CharField(max_length=60)),
                ('bairro', models.CharField(max_length=60)),
                ('cidade', models.CharField(max_length=60)),
                ('uf', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='endereco.Uf', verbose_name='UF')),
            ],
        ),
    ]
