# Generated by Django 2.1.4 on 2019-01-06 23:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Curso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=100, verbose_name='Nome')),
            ],
            options={
                'db_table': 'c_curso',
            },
        ),
        migrations.AlterModelOptions(
            name='trilha',
            options={},
        ),
        migrations.AddField(
            model_name='curso',
            name='trilha',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='curso.Trilha'),
        ),
    ]
