# Generated by Django 2.1.4 on 2019-01-11 22:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0002_auto_20190106_2357'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='trilha',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='curso.Trilha'),
        ),
    ]
