# Generated by Django 2.1.4 on 2019-01-12 00:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0003_auto_20190111_2215'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='meses',
            field=models.DecimalField(decimal_places=1, default=0, max_digits=3, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Duração (meses)'),
        ),
    ]
