# Generated by Django 2.1.4 on 2019-01-13 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0004_trilha_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='idade',
            field=models.PositiveIntegerField(default=11, verbose_name='Idade inicial'),
        ),
    ]
