# Generated by Django 2.1.4 on 2019-01-13 13:07

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0005_trilha_idade'),
    ]

    operations = [
        migrations.AddField(
            model_name='trilha',
            name='material',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=6, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Material Didádico'),
        ),
    ]
