# Generated by Django 2.1.4 on 2019-01-13 14:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curso', '0007_curso_carga_material_mensalidade_meses'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='ordem',
            field=models.PositiveIntegerField(default=0, verbose_name='Ordem na trilha'),
        ),
    ]
